name: knitly
description: A new Flutter project for knitting tracking.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core App Dependencies
  provider: ^6.1.1              # For state management
  shared_preferences: ^2.2.2    # For saving data locally
  uuid: ^4.3.3                  # For generating unique IDs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true